preprocess:
   input: "data/raw/data.csv"
   output: "data/processed/data.csv"

train:
   data:  "data/raw/data.csv"
   model: "model/model.pkl"
   n_estimators: 100
   random_state: 42
   max_depth: 5
